feat: add new apim sample
OfficeDev/TeamsFx-Samples pull request #1019
Opened 2023-09-08 03:01 UTC by KennethBWSong

2023-09-11 03:06 UTC, SLdragon commented on sso-enabled-tab-via-apim-proxy/src/components/Tab.js
> +          `cli (version < 0.11.0). Please refer to the help link for how to fix the issue: ${helpLink}`;
I think these message can be removed because it only happens for the old template

2023-09-11 06:38 UTC, MuyangAmigo requested changes

2023-09-11 06:38 UTC, MuyangAmigo commented on sso-enabled-tab-via-apim-proxy/README.md
> +
Add another paragraph:

With this sample, you can achieve the SSO feature in your tab app using OBO (on-behalf-of) flow without building a dedicated backend service.

2023-09-12 06:13 UTC, SLdragon approved these changes

2023-09-14 05:55 UTC, MuyangAmigo requested changes

2023-09-14 05:55 UTC, MuyangAmigo commented on .config/samples-config-v3.json
> +            "fullDescription": "This is a tab app with Graph Toolkit as frontend and Azure API Management as proxy to get user login information with SSO",
An SSO-enabled Microsoft Teams Tab app using APIM as a proxy.

2023-09-14 05:55 UTC, MuyangAmigo commented on .config/samples-config-v3.json
> +            "fullDescription": "This is a tab app with Graph Toolkit as frontend and Azure API Management as proxy to get user login information with SSO",
This is a Microsoft Teams tab app that can display user login information with SSO. This app uses Graph Toolkit as the frontend and Azure API Management as a proxy.

2023-09-14 05:55 UTC, MuyangAmigo commented on .config/samples-config-v3.json
> +            ],
Add SSO as a tag?

2023-09-14 06:23 UTC, blackchoey commented on sso-enabled-tab-via-apim-proxy/infra/apim.bicep
> +    secret: false
should be true?

2023-09-14 06:26 UTC, blackchoey commented on sso-enabled-tab-via-apim-proxy/infra/apim.bicep
> +    value: '<!--\r\n    IMPORTANT:\r\n    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.\r\n    - Only the <forward-request> policy element can appear
minor: maybe put the xml content to a file and let bicep read the content from that file: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-files#loadtextcontent. The readability is not so good.

Not necessary to solve in this PR.

2023-09-14 06:28 UTC, blackchoey commented on sso-enabled-tab-via-apim-proxy/infra/apim.bicep
> +    value: '<!--\r\n    IMPORTANT:\r\n    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.\r\n    - Only the <forward-request> policy element can appear
By the way, seems there's no special config in the value. Is there any way to let APIM configure with its default value?

2023-09-14 06:29 UTC, KennethBWSong commented on sso-enabled-tab-via-apim-proxy/infra/apim.bicep
> +    value: '<!--\r\n    IMPORTANT:\r\n    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.\r\n    - Only the <forward-request> policy element can appear
Sure, I will investigate and fix in another pr if possible

2023-09-14 06:33 UTC, blackchoey commented on sso-enabled-tab-via-apim-proxy/src/components/Tab.js
> +    this.scope = ["User.Read"];
minor: may put scope to config.js (we can hard code the value), this is also a kind of config

2023-09-14 06:36 UTC, blackchoey commented on sso-enabled-tab-via-apim-proxy/public/auth-end.html
> +          msalInstance.handleRedirectPromise()
maybe we don't need this in APIM scenario?

2023-09-14 06:39 UTC, blackchoey approved these changes
Can solve the comment with additional PR

2023-09-14 07:01 UTC, KennethBWSong commented on sso-enabled-tab-via-apim-proxy/src/components/Tab.js
> +    this.scope = ["User.Read"];
Fixed, thanks!

2023-09-14 07:01 UTC, KennethBWSong commented on sso-enabled-tab-via-apim-proxy/public/auth-end.html
> +          msalInstance.handleRedirectPromise()
Will fix in another pr.

2023-09-14 07:01 UTC, KennethBWSong commented on sso-enabled-tab-via-apim-proxy/aad.manifest.json
> +            "type": "Spa"
Will fix in another pr.

2023-09-14 07:01 UTC, KennethBWSong commented on sso-enabled-tab-via-apim-proxy/infra/apim.bicep
> +    secret: false
Fixed, thanks!

2023-09-14 07:03 UTC, blackchoey approved these changes

2023-09-14 07:12 UTC, MuyangAmigo approved these changes

2023-09-14 08:01 UTC, tecton commented on .config/samples-config-v3.json
> +            "gifPath": "assets/sso-enabled-tab-via-apim-proxy.gif",
Please also add a thumbnail image to show in sample gallery. The GIF will be shown in detailed page.

2023-09-15 07:45 UTC, tecton approved these changes

2023-09-15 07:57 UTC, merged