docs: add sample gallery contributing guide
OfficeDev/TeamsFx-Samples pull request #1027
Opened 2023-09-14 06:00 UTC by HuihuiWu-Microsoft

2023-09-14 06:47 UTC, tecton requested changes

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +Before your start, you might want to know whether you will need to commit your source code to our repo. In most of cases, your Teams sample source code will need to be commited to our repo, especiall
"your source code can be resides in your own open source repo": can reside in / can live in

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +Before your start, you might want to know whether you will need to commit your source code to our repo. In most of cases, your Teams sample source code will need to be commited to our repo, especiall
"We will reference to": We will refer to?

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +1. Submit your source code by creating a pull request to our repo (target `dev` branch by default), a typical project is in below structure. Make sure you have the `sampleDemo.gif` and `README.md` fi
`sampleDemo.gif` should be changed to `thumbnail.png` now.

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +      - sampleDemo.gif
Same here.

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +The sampleDemo.gif is a very short gif illustrating what users will see after the app is running, and demonstrating major usage of the sample. The gif can also be a static screenshot of the sample if
Shall we add a description of thumbnail too?

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +The README.md file basically describe what's the sample, how to run it and so on. Here is a [README Template](https://github.com/OfficeDev/TeamsFx-Samples/blob/zhany-readme-template/README_template.m
Can we also include README template in this PR?

2023-09-14 06:47 UTC, tecton commented on CONTRIBUTING.md
> +2. [Log a Issue ticket](https://github.com/OfficeDev/TeamsFx-Samples/issues/new?assignees=summzhan&labels=&projects=&template=new-sample-onboard-request.md&title=%5BSample+Onboard+Request%5D+Your+sam
Log a Issue ticket -> Log an Issue Ticket

2023-09-14 06:51 UTC, HuihuiWu-Microsoft commented on CONTRIBUTING.md
> +The README.md file basically describe what's the sample, how to run it and so on. Here is a [README Template](https://github.com/OfficeDev/TeamsFx-Samples/blob/zhany-readme-template/README_template.m
I think it might be too large. Add @summzhan here to confirm

2023-09-14 07:06 UTC, HuihuiWu-Microsoft commented on CONTRIBUTING.md
> +2. [Log a Issue ticket](https://github.com/OfficeDev/TeamsFx-Samples/issues/new?assignees=summzhan&labels=&projects=&template=new-sample-onboard-request.md&title=%5BSample+Onboard+Request%5D+Your+sam
I'd like to change it to 'Log an issue ticket' to align with other parts

2023-09-14 07:09 UTC, HuihuiWu-Microsoft commented on CONTRIBUTING.md
> +Before your start, you might want to know whether you will need to commit your source code to our repo. In most of cases, your Teams sample source code will need to be commited to our repo, especiall
Updated

2023-09-15 06:47 UTC, summzhan submitted a review, later dismissed

2023-09-15 06:47 UTC, summzhan commented on CONTRIBUTING.md
> +The README.md file basically describe what's the sample, how to run it and so on. Here is a [README Template](https://github.com/OfficeDev/TeamsFx-Samples/blob/zhany-readme-template/README_template.m
link is enough. I approve this PR

2023-09-15 07:59 UTC, HuihuiWu-Microsoft commented on CONTRIBUTING.md
> +The README.md file basically describe what's the sample, how to run it and so on. Here is a [README Template](https://github.com/OfficeDev/TeamsFx-Samples/blob/zhany-readme-template/README_template.m
Updated

2023-09-18 06:14 UTC, merged