feat: add new sample bot-sso-docker
OfficeDev/TeamsFx-Samples pull request #1122
Opened 2024-01-05 09:14 UTC by hund030

2024-01-09 06:21 UTC, MuyangAmigo commented on bot-sso-docker/README.md
I‘d suggest we add a dedicated section to talk about the development with container, including some background info plus how to containerize a Teams app and some references for further development scenairos.

2024-01-10 05:34 UTC, hund030 commented on bot-sso-docker/README.md
Updated. I have added a section about how to containerize Teams app and next step I will add more information about CD and AKS.

2024-01-11 08:51 UTC, hund030 commented on bot-sso-docker/teamsapp.yml
> +      run: echo "::set-teamsfx-env CONTAINER_IMAGE=sso-bot:latest"
In samples, Teams app name, AAD app name, and bot name are all in hard code. User should update the names by themselves. 
The `latest` tag is omitted.

2024-01-15 07:18 UTC, eriolchan commented on bot-sso-docker/teamsapp.yml
> +    name: set environment variables
Can these 2 set env variable combined to one step?

2024-01-17 05:47 UTC, hund030 commented on bot-sso-docker/teamsapp.yml
> +    name: set environment variables
No. Because the second variable depends on the first one, TTK cannot handle it in one step.

2024-01-17 07:05 UTC, hund030 commented on bot-sso-docker/README.md
> +| ------------ | ---------- | -------------------------------------- |
Updated.

2024-01-19 15:07 UTC, therealjohn requested changes
There are a lot of files scaffolded in this sample - is there anything we can do to trim them down? It would help if the bot source was organized in a directory too, like other samples in `src/`.

2024-01-19 15:07 UTC, therealjohn commented on bot-sso-docker/appPackage/manifest.json
> +        "short": "sso-bot${{APP_NAME_SUFFIX}}",
Minor, but a friendlier default name: `"SSO Bot (${{APP_NAME_SUFFIX}})"`

2024-01-19 15:07 UTC, therealjohn commented on bot-sso-docker/infra/azure.parameters.json
> +      "value": "sso-bot"
Same here, a better default for these names is preferred: `SSO Bot`

2024-01-19 15:07 UTC, therealjohn commented on bot-sso-docker/cli.md
> +## Try sample with TeamsFx CLI
Could this instruction be moved to the README?

2024-01-22 07:16 UTC, hund030 commented on bot-sso-docker/cli.md
> +## Try sample with TeamsFx CLI
There is similar content in README. I add this document to follow the convention that most samples have such a cli.md to describe how to try the sample with the CLI.

2024-01-22 08:48 UTC, hund030 commented
> There are a lot of files scaffolded in this sample - is there anything we can do to trim them down? 

@therealjohn This sample is designed as a container solution for [the SSO Bot sample](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/bot-sso). I copy most of content from that sample and I think there is no file can be omitted.

> It would help if the bot source was organized in a directory too, like other samples in `src/`.

I agree. Let me also update the folder structure in the original sample, too.

2024-01-23 02:56 UTC, eriolchan approved these changes

2024-01-25 13:47 UTC, therealjohn approved these changes

2024-01-26 02:54 UTC, merged