feat(bot): simple bot with sso TS
OfficeDev/TeamsFx-Samples pull request #127
Opened 2021-09-10 06:53 UTC by YitongFeng-git

2021-09-13 18:54 UTC, teemobean requested changes
Added some comments around the generalization for handling commands. Thank you!

BTW "helplers" folder is spelled wrong.

2021-09-13 18:54 UTC, teemobean commented on bot-sso/ts/bot/helplers/commandHelpler.ts
> +export class CommandsHandler {
Should we name the class the same as the file? BTW the file is spelled wrong. "Helper".

2021-09-13 18:54 UTC, teemobean commented on bot-sso/ts/bot/helplers/botCommand.ts
> +export interface BotCommand {
It may be better for this and BotCommand to be either both a class or both an interface. Since BotCommand has to be a class, maybe make this a class. This way a developer's experience around these two entities are the same.

2021-09-13 18:54 UTC, teemobean commented on bot-sso/ts/bot/helplers/botCommand.ts
> +  commandKey: string;
I think in simple cases a command key is ok. But I think we should support complex scenarios where the determination of whether this command should handle this message is more complicated than a match. So maybe introduce a base method here that does the simple string match but a specialization can override if necessary?

2021-09-13 18:54 UTC, teemobean commented on bot-sso/ts/bot/helplers/commandHelpler.ts
> +    if(!this.commandInstanceMap.has(commandKey)){
Same comment here - perhaps this is too limiting. Maybe a more generalized approach can be useful here.

2021-09-15 01:38 UTC, YitongFeng-git commented on bot-sso/ts/bot/helplers/botCommand.ts
> +  commandKey: string;
OK I see，will add such a match function

2021-09-15 16:48 UTC, timngmsft requested changes

2021-09-15 16:48 UTC, timngmsft commented on bot-sso/ts/bot/commands/learn.ts
> +        `Run "learn" command failed! Do not have input "likeCount"`
How about this for the error message?
`Command "learn" failed: missing input "likeCount"`

2021-09-15 16:48 UTC, timngmsft commented on bot-sso/ts/bot/commands/showUserProfile.ts
> +    await context.sendActivity("Call Microsoft Graph on behalf of user...");
"Retrieving user information from Microsoft Graph ..."

2021-09-15 16:48 UTC, timngmsft commented on bot-sso/ts/bot/commands/showUserProfile.ts
> +        "Getting profile from Microsoft Graph failed! "
"Could not retrieve profile information from Microsoft Graph."

2021-09-15 22:37 UTC, timngmsft requested changes

2021-09-15 22:37 UTC, timngmsft commented on bot-sso/ts/bot/commands/showUserProfile.ts
> +      "User.Read",
One follow up on this - I noticed that this is "User.Read" vs ".default" in the Tab app. Can you follow up with @adashen on this difference?

2021-09-16 02:12 UTC, YitongFeng-git commented on bot-sso/ts/bot/commands/showUserProfile.ts
> +      "User.Read",
ok, is in discussion

2021-09-16 02:48 UTC, YitongFeng-git commented on bot-sso/ts/bot/commands/showUserProfile.ts
> +      "User.Read",
In Tab app, it is "user.read" as well: const { scope } = { scope: ["User.Read"], ...options };

2021-09-17 00:27 UTC, teemobean approved these changes

2021-09-17 00:28 UTC, timngmsft approved these changes

2021-09-23 05:55 UTC, merged