chore: add release samples and sample list to cd
OfficeDev/TeamsFx-Samples pull request #498
Opened 2022-09-26 06:42 UTC by yukun-dong

2022-09-26 07:05 UTC, hund030 commented on .github/workflows/cd.yml
> +        run: git tag | grep v > ${{ runner.temp }}/sample-tags.txt
`grep v` looks dangerous.

2022-09-26 07:05 UTC, hund030 commented on .github/workflows/cd.yml
> +          fetch-depth: 0
Why do we need to get all history?

2022-09-26 07:07 UTC, hund030 commented on .github/workflows/cd.yml
> +          allowUpdates: true
I wonder what if user downloads the sample zip while we are updating it?

2022-09-26 07:10 UTC, hund030 commented on .github/workflows/cd.yml
> +      - name: update sample tag list release
I think uploading tag list should be the last step. Otherwise, there will be invalid tag in it before release done.

2022-09-26 07:18 UTC, yukun-dong commented on .github/workflows/cd.yml
> +          fetch-depth: 0
To get all the tags. I will see if there is other way to get the tags.

2022-09-26 07:23 UTC, yukun-dong commented on .github/workflows/cd.yml
> +          allowUpdates: true
Indeed this is a problem. I add `allowUpdates: true` here because L28 supports updating tag to the top. It would be strange if tag is updated while released zips are not updated.

2022-09-26 07:24 UTC, yukun-dong commented on .github/workflows/cd.yml
> +      - name: update sample tag list release
That's why `grep` is needed, to only keep tags for samples.

2022-09-27 06:44 UTC, JerryYangKai commented
Looks good to me, zhijie's comment also is what I want to ask.
Another thing I want to double confirm, the 'project id' in projectSettings.json is add by Coordinator after the scaffold, right?

2022-10-13 08:21 UTC, wenytang-ms commented on .github/sample-list.json
> +{
once there add a sample, developer needs to update this file, how to reminder they do not forget this?

2022-10-13 08:21 UTC, wenytang-ms commented on .github/sample-list.json
> +{
why not list by script or any other way?

2022-10-13 09:08 UTC, wenytang-ms commented
it's better to run on this action in your own repo.

2022-10-14 02:54 UTC, JerryYangKai commented on .github/sample-list.json
> +{
I think other ways also will including addtional problem when onborading sample.
I agreed with wenyu we need a place to reminder, from my side the most efficient way is provide a contribute guide in our repo. Just like onborading template in TeamsFx repo.

2022-10-14 02:55 UTC, JerryYangKai approved these changes

2022-10-14 03:23 UTC, wenytang-ms requested changes
Just block this PR merge before this sprint release finished to reduce the possibility of release errors.

2022-10-14 06:29 UTC, yukun-dong commented on .github/workflows/cd.yml
>            INITIAL_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
Indeed the logic here is wrong, but I just found that action anothrNick/github-tag-action will try to find the latest tag version like "v0.0.0", if no tag found it will then use INITIAL_VERSION. Therefore the "get latest tag" step is not needed here. (details: https://github.com/anothrNick/github-tag-action/blob/1ffbb2e04bd950cffea99066469cb16d69a7887e/entrypoint.sh#L70-L87)

2022-10-14 06:43 UTC, yukun-dong commented on .github/sample-list.json
> +{
> why not list by script or any other way?

If I understand correctly, you are suggesting using command like "ls" to list all sample folders. The potential problem is that in CD environment there might be other files or folders created. So I think it's better to keep this json and provide a contribution guide.

2022-10-24 06:07 UTC, IvanJobs commented on .github/workflows/cd.yml
> +        if: ${{ github.event_name == 'workflow_dispatch'&& github.ref != 'refs/heads/release' }}
Nit: The condition can be refined a little bit to something like `github.inputs.preid == ['rc', 'stable'] && github.ref != 'refs/heads/release'`.  
Since according to the comment, it doesn't matter if the github.event_name is 'workflow_dispatch' or 'schedule' - both are okay, but the actual limitation is stable/rc must come from release branch.

Based on the current logic, we cannot publish zips from dev branch manually.

2022-10-24 06:22 UTC, IvanJobs approved these changes
lgtm

2022-10-24 06:47 UTC, wenytang-ms commented on .github/workflows/cd.yml
> +          fetch-depth: 0
you may test with fetch-depth as 1, maybe action can also fetch history tags

2022-10-24 06:50 UTC, qinezh commented on .github/workflows/cd.yml
> +      - name: release templates' RC version to github
typo? 
```suggestion
      - name: release samples' RC version to github
```

2022-10-24 06:55 UTC, yukun-dong commented on .github/workflows/cd.yml
> +      - name: release templates' RC version to github
Thanks, updated.

2022-10-24 07:13 UTC, yukun-dong commented on .github/workflows/cd.yml
> +          fetch-depth: 0
Yes, I removed `fetch-depth` part and it works. 1 is the default value for `fetch-depth`.

2022-10-24 07:46 UTC, wenytang-ms approved these changes

2022-10-24 07:50 UTC, merged