feat: update samples to use TeamsFx and TeamsFx-React V2
OfficeDev/TeamsFx-Samples pull request #524
Opened 2022-11-02 05:45 UTC by yiqing-zhao

2022-11-04 05:46 UTC, SLdragon approved these changes

2022-11-04 05:48 UTC, KennethBWSong approved these changes
Approve for nonssotab

2022-11-04 05:49 UTC, kuojianlu approved these changes

2022-11-04 05:58 UTC, formulahendry commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +        // Initialize Graph Toolkit TeamsFx provider
Graph Toolkit?

2022-11-04 06:00 UTC, formulahendry commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +        throw err;
Seems no need to try-catch and throw?

2022-11-04 06:05 UTC, formulahendry commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +              Hello{data ? ", " + data.profile.displayName : ""}!
`data` will always be true here?

2022-11-04 06:06 UTC, formulahendry commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +      {!loading && data === undefined && (
`data === undefined` -> `!data`?

2022-11-04 06:12 UTC, yiqing-zhao commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +              Hello{data ? ", " + data.profile.displayName : ""}!
`data` can be undefined.

2022-11-04 06:12 UTC, formulahendry requested changes
Leave some small comments~

2022-11-04 06:14 UTC, formulahendry commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +              Hello{data ? ", " + data.profile.displayName : ""}!
Since this code block is after `!loading && data`,  this `data` may not have chance to be undefined

2022-11-04 06:56 UTC, yiqing-zhao commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +      {!loading && data === undefined && (
Updated to `!data`, thanks!

2022-11-04 06:57 UTC, yiqing-zhao commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +              Hello{data ? ", " + data.profile.displayName : ""}!
Thanks for comments! Updated.

2022-11-04 06:57 UTC, yiqing-zhao commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +        throw err;
Agreed. Try-Catch is removed, thx!

2022-11-04 06:59 UTC, formulahendry approved these changes

2022-11-04 06:59 UTC, yiqing-zhao commented on graph-connector-app/tabs/src/components/sample/Welcome.tsx
> +        // Initialize Graph Toolkit TeamsFx provider
Since no graph toolkit UI is used in the sample, removed `@microsoft/mgt-element` and `@microsoft/mgt-teamsfx-provider`, and the following lines:
```
const provider = new TeamsFxProvider(teamsfx, scope);
Providers.globalProvider = provider;
Providers.globalProvider.setState(ProviderState.SignedIn);
```

2022-11-04 08:39 UTC, SLdragon approved these changes

2022-11-07 02:26 UTC, hund030 approved these changes

2022-11-07 02:27 UTC, merged