Add a combined project sample for Teams tab and Outlook add-in
OfficeDev/TeamsFx-Samples pull request #685
Opened 2023-02-24 09:00 UTC by 1yefuwang1

2023-02-28 07:34 UTC, MuyangAmigo commented on teams-tab-with-outlook-addin/README.md
> +
This section is not relevant, we should remove it.

2023-02-28 07:34 UTC, MuyangAmigo commented on teams-tab-with-outlook-addin/README.md
> +
This section is also not relevant, can we remove it?

2023-02-28 07:34 UTC, MuyangAmigo commented on teams-tab-with-outlook-addin/README.md
> +
Does remote preview work this way?

2023-02-28 07:34 UTC, MuyangAmigo commented on teams-tab-with-outlook-addin/README.md
> +
How to use this Hello World Teams tab and Outlook Add-in sample app

2023-02-28 07:34 UTC, MuyangAmigo commented on teams-tab-with-outlook-addin/README.md
> +
Microsoft Teams supports the ability to run web-based UI inside "custom tabs" that users can install either for just themselves (personal tabs) or within a team or group chat context.

Outlook add-ins are integrations built by third parties into Outlook by using our web-based platform. 

Now you have the ability to create a single unit of distribution for all your Microsoft 365 extensions by using the same manifest format and schema, based on the current JSON-formatted Teams manifest.

2023-03-01 14:37 UTC, MuyangAmigo requested changes

2023-03-01 14:37 UTC, MuyangAmigo commented on hello-world-teams-tab-and-outlook-addin/README.md
> +
This is not correct, it should be the Teams Toolkit Prerelease version.

2023-03-01 14:37 UTC, MuyangAmigo commented on hello-world-teams-tab-and-outlook-addin/README.md
> +- An M365 account. If you do not have M365 account, apply one from [M365 developer program](https://developer.microsoft.com/en-us/microsoft-365/dev-program)
It should be Outlook Desktop Client on Windows?

2023-03-01 14:37 UTC, MuyangAmigo commented on hello-world-teams-tab-and-outlook-addin/README.md
> +
It should be `manifest.json`. and Remove the mention of "Teams app", just "app" is fine.

2023-03-01 14:37 UTC, MuyangAmigo commented on hello-world-teams-tab-and-outlook-addin/README.md
> +
Title can change to Preview the app? Or does Teams / Outlook portion previews differently?

2023-03-01 15:08 UTC, MuyangAmigo commented on hello-world-teams-tab-and-outlook-addin/README.md
> +
Can we also add a note here to remind developers that they need to use the same account in Teams Toolkit as logged in to Outlook

2023-03-02 01:59 UTC, 1yefuwang1 commented on hello-world-teams-tab-and-outlook-addin/README.md
> +
Preview here means launch remote, which is not supported with one click F5 for Outlook.

2023-03-02 05:15 UTC, MuyangAmigo approved these changes

2023-03-02 05:23 UTC, merged