Kaiyan/readme
OfficeDev/TeamsFx-Samples pull request #751
Opened 2023-03-17 03:21 UTC by JerryYangKai

2023-03-17 03:23 UTC, JerryYangKai commented
@zyxiaoyuer Please help review, thanks

2023-03-20 07:22 UTC, summzhan commented on hello-world-in-meeting/README.md
> +- Use Teams Toolkit to create a Teams meeting app.
How to use...

2023-03-20 07:22 UTC, summzhan commented on hello-world-in-meeting/README.md
> +- Use Teams SDK to get context data in Teams app.
TeamsFx SDK？

2023-03-20 07:25 UTC, summzhan commented on hello-world-in-meeting/README.md
> +| Mar 16, 2023 | Kai    | first version |
I remember in V4 we already have this in-meeting sample.
So please add one line history for TTK V4.

2023-03-20 07:25 UTC, summzhan requested changes
please resolve the comments in line

2023-03-20 08:14 UTC, JerryYangKai commented on hello-world-in-meeting/README.md
> +- Use Teams Toolkit to create a Teams meeting app.
Fixed

2023-03-20 08:14 UTC, JerryYangKai commented on hello-world-in-meeting/README.md
> +- Use Teams SDK to get context data in Teams app.
Teams client lib, in this sample we have not used teamsfx sdk

2023-03-20 08:15 UTC, JerryYangKai commented on hello-world-in-meeting/README.md
> +| Mar 16, 2023 | Kai    | first version |
Fixed

2023-03-20 08:19 UTC, JerryYangKai commented
> please resolve the comments in line

@summzhan  Thanks for reviewing this, I have pushed a new commit and fix the readme

2023-03-22 09:02 UTC, summzhan approved these changes

2023-03-22 09:09 UTC, merged