chore: update README for m365 samples
OfficeDev/TeamsFx-Samples pull request #780
Opened 2023-03-28 10:15 UTC by kuojianlu

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17554156

2023-03-28 10:23 UTC, swatDong submitted a review, later dismissed

2023-03-31 06:57 UTC, summzhan commented on NPM-search-connector-M365/README.md
> -> This warning will be removed when the samples are ready for production.
the note in line3 to line 5 need to be kept.

2023-03-31 06:58 UTC, summzhan commented on NPM-search-connector-M365/README.md
> +1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
don't need line 21 since VSC is mentioned as prerequsites.

2023-03-31 06:59 UTC, summzhan commented on NPM-search-connector-M365/README.md
> +### Preview the app
since this app can run in outlook, hence in line 29 we can change it to "Preview the app in Teams"

2023-03-31 07:01 UTC, summzhan commented on NPM-search-connector-M365/README.md
> +| Nov 9, 2021 | swatDong | add to support Teams Toolkit v2.10.0 |
the sequence is from lower version to higher verion. So the latest updates in last row.

2023-03-31 07:02 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
> -
same here, keep the note. Sorry I forget the note in template, my bad.

2023-03-31 07:03 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
> +1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
remove line 23

2023-03-31 07:07 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
> +## Advanced usage of this sample
The "advanced usage xxx" section is reserved for customization of sample app. What you described here is jusr basic usage of the app. I think you can merge the step 1 and 2 (line35-38) to "Preview the app" section and remove the rest. 
if you don't want to delete the rest content you can keep them in "Preview the app" section. depends on you.

2023-03-31 07:11 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
>  ### Code structure
"Code structure" and "Architecture" is not requried in new template, we would like to keep it simple. So remove them.

2023-03-31 07:12 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
> +## Version History
the sequence of version history is from lower version to higher version.

2023-03-31 07:12 UTC, summzhan requested changes
commented in line

2023-03-31 07:13 UTC, kuojianlu commented on NPM-search-connector-M365/README.md
> +### Preview the app
This step is to preview the app in Teams or Outlook, so I think "Preview the app" is better?

2023-03-31 07:16 UTC, kuojianlu commented on todo-list-with-Azure-backend-M365/README.md
>  ### Code structure
Will remove. I see this sample still has "Architecture": https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/todo-list-with-Azure-backend#architecture.

2023-03-31 07:26 UTC, kuojianlu commented on NPM-search-connector-M365/README.md
> +### In Outlook
Updated.

2023-03-31 07:27 UTC, kuojianlu commented on todo-list-with-Azure-backend-M365/README.md
> +## Advanced usage of this sample
Updated.

2023-03-31 07:28 UTC, kuojianlu commented on todo-list-with-Azure-backend-M365/README.md
> +## Advanced usage of this sample
This sample has the same issue: https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/todo-list-with-Azure-backend#advanced-usage-of-this-sample

2023-04-06 03:01 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
>  ### Code structure
@formulahendry could you help remove the architecture section of your sample README?

2023-04-06 03:02 UTC, summzhan commented on todo-list-with-Azure-backend-M365/README.md
> +## Advanced usage of this sample
@formulahendry can you move the content in "advanced usage of this sample" to "Preview the app" section? since the content is basic usage in preview, not advanced usage.

2023-04-06 03:04 UTC, summzhan approved these changes

2023-04-06 03:06 UTC, merged