docs: update readme to v5.0
OfficeDev/TeamsFx-Samples pull request #784
Opened 2023-03-29 11:07 UTC by hund030

2023-03-31 08:26 UTC, summzhan commented on hello-world-bot-with-tab/README.md
> +
need to add ### Preview the app in Teams

2023-03-31 08:27 UTC, summzhan commented on hello-world-bot-with-tab/README.md
> +## Add Single Sign On feature
Can you change the title to "## Advanced usage of this sample"
Then followed with "### Add Single Sign On feaure"

2023-03-31 08:57 UTC, summzhan commented on hello-world-tab-with-backend/README.md
> +- Use Teams Toolkit to create a Teams tab app.
"How to use xxx"

2023-03-31 08:57 UTC, summzhan commented on hello-world-bot-with-tab/README.md
> +- Use Teams Toolkit to create a Teams app with both Bot and Tab capabilities.
"How to use xxx"

2023-03-31 09:02 UTC, summzhan requested changes
comment in line

2023-03-31 10:03 UTC, hund030 commented on hello-world-bot-with-tab/README.md
> +|Dec 9, 2022| hund030 | update to support Teams Toolkit v5.0.0|
This sample is for v5 only and there is no v4 history for it.

2023-03-31 10:49 UTC, hund030 commented on hello-world-bot-with-tab/README.md
> +A bot, chatbot, or conversational bot is an app that responds to simple commands sent in chat and replies in meaningful ways. Examples of bots in everyday use include: bots that notify about build fa
Updated

2023-04-06 02:56 UTC, summzhan commented on hello-world-bot-with-tab/README.md
> +|Dec 9, 2022| hund030 | update to support Teams Toolkit v5.0.0|
Then you should make it clear in Comments column. For example use words like "Onboard sample in Teams Toolkit V5.0.0"

2023-04-06 03:05 UTC, hund030 commented on hello-world-bot-with-tab/README.md
> +|Dec 9, 2022| hund030 | update to support Teams Toolkit v5.0.0|
Good suggestion. Updated.

2023-04-06 03:11 UTC, summzhan approved these changes

2023-04-06 03:16 UTC, merged