chore: add back SPFx 1.16.1 updates and update readme
OfficeDev/TeamsFx-Samples pull request #786
Opened 2023-03-30 02:51 UTC by HuihuiWu-Microsoft

2023-03-30 02:52 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
> -
I keep the 'Architecture' and 'Further reading' parts for now. @summzhan Feel free to let me know if you think we need to remove this.

2023-03-31 06:17 UTC, summzhan commented on todo-list-SPFx/README.md
> +* [Teams Toolkit for VS Code](https://aka.ms/teams-toolkit) or [TeamsFx CLI](https://aka.ms/teamsfx-cli)
line 26 should be placed in Prerequsites section. Remove it from steps.

2023-03-31 06:22 UTC, summzhan commented on todo-list-SPFx/README.md
>  1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
line 53 is not necessary if it's mentioned in prerequsites.

2023-03-31 06:23 UTC, summzhan commented on todo-list-SPFx/README.md
> -
It's ok to keep it.

2023-03-31 06:24 UTC, summzhan commented on todo-list-SPFx/README.md
> +|Mar 23, 2023| huihuiwu | update to support Teams Toolkit v5.0.0|
can you add a version history for Teams Toolkit v4.0.0 update? Since 4.0.0 was a major updates which include a folder structure change too, and other samples added that history as well.

2023-03-31 06:25 UTC, summzhan requested changes
comments in line

2023-03-31 06:29 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
> +* [Teams Toolkit for VS Code](https://aka.ms/teams-toolkit) or [TeamsFx CLI](https://aka.ms/teamsfx-cli)
Current section is Prerequisite section instead of Steps section

2023-03-31 06:29 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
>  1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
Will update to remove it

2023-03-31 07:09 UTC, summzhan commented on todo-list-SPFx/README.md
Please help remove the note in line 3-5

2023-03-31 07:17 UTC, summzhan commented on todo-list-SPFx/README.md
> -
Since we got feedbacks that the sample README file contains too much contents that not "that important". We want to keep the README file simple and focus on important messages. Hence it's better to remove the architecture section. And keep this file the same sturcture with other sample READMEs. 

For Further reading parts. the contents was special for SPFx, so can keep it.

2023-03-31 10:14 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
Updated

2023-03-31 10:14 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
> -
Updated

2023-03-31 10:15 UTC, HuihuiWu-Microsoft commented on todo-list-SPFx/README.md
> +|Mar 23, 2023| huihuiwu | update to support Teams Toolkit v5.0.0|
Updated

2023-04-06 02:54 UTC, summzhan approved these changes

2023-04-06 02:56 UTC, merged