docs(v5): Update README file for sample
OfficeDev/TeamsFx-Samples pull request #788
Opened 2023-03-30 09:46 UTC by XiaofuHuang

[Task 17554185](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17554185): Update README file for sample owned by xiaofu

2023-03-31 03:12 UTC, kuojianlu submitted a review, later dismissed

2023-03-31 09:02 UTC, summzhan commented on adaptive-card-notification/README.md
> +- Use Adaptive Cards to send notification in Teams.
change to "How to use"

2023-03-31 09:04 UTC, summzhan commented on adaptive-card-notification/README.md
>  1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
don't need to ask use download Teams Toolkit in step by step guides, because in prerequsite we already require uses to install Teams Toolkit. so just delete this line.

2023-03-31 09:05 UTC, summzhan commented on incoming-webhook-notification/README.md
>  - A [Teams Channel](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
in the prerequsite, we should mention Teams Toolkit as well.

2023-03-31 09:06 UTC, summzhan commented on incoming-webhook-notification/README.md
>  - A [Teams Channel](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
Does this sample can run without Teams Toolkit?

2023-03-31 09:07 UTC, summzhan commented on stocks-update-notification-bot-dotnet/README.md
> +- Use a bot in different contexts
again, use "How to use xxx"

2023-03-31 09:08 UTC, summzhan commented on stocks-update-notification-bot-dotnet/README.md
>  1. Download [Visual Studio](https://visualstudio.microsoft.com/) and install [Teams Toolkit for Visual Studio Extension](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio
don't need to ask user download Teams Toolkit since we already asked user to install in prerequsites section. just delete line 20

2023-03-31 09:09 UTC, summzhan commented on stocks-update-notification-bot/README.md
>  1. Download [Visual Studio Code](https://code.visualstudio.com) and install [Teams Toolkit Visual Studio Code Extension](https://aka.ms/teams-toolkit).
don't need line 22

2023-03-31 09:10 UTC, summzhan requested changes
commented in line.

2023-04-03 02:40 UTC, XiaofuHuang commented
> commented in line.

Updated according to the comments

2023-04-06 03:14 UTC, summzhan approved these changes

2023-04-06 03:18 UTC, merged